### ISSUE TITLE
Create a TOC to github pages

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/.github#21]
### Story

As a reader, if I open openfoodfacts.github.io/, I should get a link to every existing project pages and maybe a short introduction to open food facts.

### TODO

- [] create a index.md page
- [] create a CI action to compile the page and publish it on openfoodfacts.github.io/
- [] configure for publication
